# Generated by Django 3.0.7 on 2020-06-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleMultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizId', models.IntegerField(default=0)),
                ('quiz', models.TextField(default='')),
                ('option1', models.TextField(default='')),
                ('option2', models.TextField(default='')),
                ('option3', models.TextField(default='')),
                ('ansIndex', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rule_multiple_choice',
            },
        ),
        migrations.CreateModel(
            name='RuleTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizId', models.IntegerField(default=0)),
                ('quiz', models.TextField(default='')),
                ('ansIndex', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rule_true_false',
            },
        ),
    ]
